### ISSUE TITLE
请教A组件中的storyboard该怎么处理？

### ISSUE THREAD

**Issue by archerLj** [ModulizationDemo/A#1]
Casa, 你好，看了您的组件化方案大受启发，但是有个问题：

组件A中的storyboard该怎么处理呢？如果把它和用到的图片都放到bundle中，后面开发的话会很麻烦了。您有什么好的建议吗？

**Comment by casatwy** [comment]
你原来组件处理storyboard的方法不变啊，因为target-action跟storyboard或者图片都是无关的
